# This action is to rebuild every friday so that we pick up new episodes

name: "Rebuild to pick up new episode"

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "30 8 * * FRI"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAST_TRAIN_POD }}"
          channelId: live
          projectId: last-train-pod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
